[package]
name = "rustlib"
version = "0.1.0"
authors = ["Rajni Kant"]
description = "Sample library in rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rajnikantwebdev/rust-lib"
repository = "https://github.com/rajnikantwebdev/rust-lib"
edition = "2021"

[dependencies]
